BlockStreet:
  Version: 2.0.0                # Do not change this, it is used for internal purposes
  InterestInterval: 10
  Updates:
    Remainder: true
  StockCrash:
    DangerZonePercentage: 0.25
    CrashChance: 0.1