BlockStreet:
  Version: 2.0.0                # Do not change this, it is used for internal purposes
  InterestInterval: 10
  Updates:
    Remainder: true
  StockCrash:
    Enabled: true              # Enable or disable stock crashes.
    Aggressiveness: 0.7        # Value between 0 and 1. A higher value means more frequent crashes.
  Taxes:
    CompanyCreation:           # Tax applied when creating company, applied over the valuation, per risk level
      - 0.1                    # Risk 1
      - 0.2                    # Risk 2
      - 0.3                    # Risk 3
      - 0.4                    # Risk 4
      - 0.5                    # Risk 5