BlockStreet:
  Version: 2.0.0                # Do not change this, it is used for internal purposes
  InterestInterval: 10
  Updates:
    Remainder: true
  StockCrash:
    Aggressiveness: 0.7        # Value between 0 and 1. A higher value means more frequent crashes.